export const applicationId: any = process.env.APPLICATION_ID;
export const guildId: any = process.env.GUILD_ID;
export const token: any = process.env.BOT_TOKEN;
export const voiceChannelId: any = process.env.VOICE_CHANNEL_ID;
export const mehmaanChannelId: any = process.env.MEHMAAN_CHANNEL_ID;
export const categoryId: any = process.env.CATEGORY_ID;
export const idleCategoryId: any = process.env.IDLE_CATEGORY_ID;
export const defaultUserLimit: any = 5 || process.env.DEFAULT_USER_LIMIT;
export const defaultBitrate: any = 96000 || process.env.DEFAULT_BITRATE;
